currentDeployment: default
deploymentConfigurations:
- name: default
  version: 2.17.1
  providers:
    kubernetes:
      enabled: true
      accounts:
      - name: spinnaker
        providerVersion: V2
        serviceAccount: true
        onlySpinnakerManaged: true
      primaryAccount: spinnaker
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: spinnaker
    location: spinnaker
  persistentStorage:
    persistentStoreType: s3
    s3:
      bucket: spinnaker
      rootFolder: front50
      pathStyleAccess: true
      endpoint: http://minio.spinnaker:9000
      accessKeyId: minio
      secretAccessKey: MINIO_PASSWORD
  features:
    artifacts: true
  security:
    apiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: https://PUBLIC_ENDPOINT/api/v1
    uiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: https://PUBLIC_ENDPOINT
  artifacts:
    http:
      enabled: true
      accounts: []